#!/bin/bash

IP=$(ip addr show | grep -v -e inet6 -e 127.0.0.1 | grep inet | cut -d ' ' -f 2 | head -1)
NET=$(ipcalc ${IP} -n | grep Network | awk '{print $2}')

BLACK='\033[0:30m'        
DGRAY='\033[1;30m'
RED='\033[0;31m'
LRED='\033[1;31m'
GREEN='\033[0;32m'
LGREEN='\033[1;32m'
ORANGE='\033[0;33m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
LBLUE='\033[1;34m'
PURPLE='\033[0;35m'
LPURPLE='\033[1;35m'
CYAN='\033[0;36m'
LCYAN='\033[1;36m'
LGRAY='\033[0;37m'     
WHITE='\033[1;37m'
NC='\033[0m'

function hili {
	cat | sed '/Starting/d' | perl -pe 's/(Nmap)/\n--\n$1/' \
	| perl -pe "s/(\d+\.\d+\.\d+\.\d+)/${LCYAN}\$1${NC}/g" \
	| perl -pe "s/([A-F0-9]+:[A-F0-9]+:[A-F0-9]+:[A-F0-9]+:[A-F0-9]+:[A-F0-9]+)/${LCYAN}\$1${NC}/g" \
	| perl -pe "s/(Host is up|open)/${LGREEN}\$1${NC}/g" \
	| perl -pe "s/(Nmap done:.*$)/${LGRAY}\$1${NC}/g"
}

function iplist {
	cat | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | sed 's/Nmap scan report for //'
}
